# Conclusion

It is a good indicator that the US fetal death number is decreasing. With the development of medical technology, economic status, and public attention to fertility quality, we can forecast that the fetal death number may be lower in the future. We found some geographical patterns in the distribution of fetal death: states near coasts tend to have higher fetal death numbers, and states in the north tend to have lower fetal death numbers. By checking the selected fetal characteristics, we found that infants with weights from 350-999 grams have much higher death numbers than infants have other weights do; as the number of births increases in a single pregnancy, fetuses are more likely to die. By further checking the delivery methods, we find that more single birth died from vaginal delivery, and more twins, triplets, quadruplets or higher died from cesarean delivery. Moreover, fetuses with a gestational age of 20-23 weeks have extremely high fetal death numbers.
From the perspective of parental characteristics, we figure out that fetal death numbers are always higher when mothers and fathers are of the same age; Black or African American mothers are more likely to get pregnant while unmarried and cause more fetal deaths.

The main limitation of our research is that, rather than the fetal death rate, we can only get the fetal death numbers. The fetal death rate is always more valuable and persuasive as it also considers birth numbers. Besides, we can only get data from 2005 to 2019, which may be outdated. From 2020 till now, we believe there have been considerable fluctuations in fetal death because, in these years, we experienced the COVID-19, challenges in abortion rights, and wars.

Therefore, to improve our research, we would like to include the birth statistics to make sure we can filter out the anomalies caused by changes in birth rates and do more research on fetal death rates. In addition, we believe an update to our data is necessary, either from the perspective of time or variables. If possible, we would like to do more research on the changes in fetal death rates in recent years. For instance, if the leading causes of fetal deaths changed and the relationships between the features changed.

In conclusion, after visualizing the fetal death statistics, we have a more thorough understanding of how fetal deaths distribute over different features. Even though CDC Wonder has a dependable and huge database, we still need to use the data carefully, as it may be incomplete or inconsistent. It is always good to check if additional information or sources are needed except for a single dataset.


