--- 
title: "Research on Fetal Deaths"
author: "Jiayi Yuan (jy3162) & Yayun Luo (yl4832)"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

```{r}
#install.packages("bookdown")
browseURL("docs/index.html")
```

The fetal mortality rate is the measure of poor reproductive health outcomes. It also indicates to some extent a country's medical and health level, economic level and basic implementation level. As the most advanced developed country in the world, the United States is famous for its advanced medical technology and strong economic strength. However, the United States ranks very high in fetal mortality. The fetal mortality rate in the United States is even three times that of some developed countries (such as Japan and Sweden), which shows that fetal mortality is a serious issue that needs to be taken seriously.


We believe that the death of a fetal is not only a sad tragedy for the family, but also has a very negative impact on an Aging American society. Therefore, in this project, we aim to explore the causes of fetal death. We will analyze the distribution of fetal mortality in the United States from the perspective of time and space. We will also examine whether specific characteristics of parents contribute to fetal mortality.

<<<<<<< HEAD
For more details of our project, please check out [**GitHub repository**](https://github.com/MiraYuan/FetalDeath) or copy the following link https://github.com/MiraYuan/FetalDeath and paste it in your browser. 
=======
This project is completed by Jiayi Yuan(JY3162) and Yayun Luo(YL4823). The following link contains all the project content: https://github.com/MiraYuan/FetalDeath.



ehfgegeuyifgeiufgei
>>>>>>> 1d58ba80ac112e95fccf5f3377175e531faa2b9c
